version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        applies-to: version-updates
        patterns:
          - "@aws-sdk/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint*"
    open-pull-requests-limit: 99
    reviewers:
      - kpfefferle
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - kpfefferle
