# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:8
      environment:
        JOBS: 2
  working_directory: ~/ember-cli-deploy-cloudfront

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --no-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint_js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS
          command: yarn run lint:js

  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test

workflows:
  version: 2
  lint_and_test:
    jobs:
      - install_dependencies
      - lint_js:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
